# Generated by Django 5.2.1 on 2025-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
